.github/workflows/ci.yaml, .github/workflows/docker-build-push.yaml, .github/workflows/node-installer.yaml, .github/workflows/release.yaml, node-installer/Dockerfile, node-installer/Makefile, node-installer/README.md, node-installer/script/installer.sh
- Adds node-installer.yaml to publish a custom node installer image with only the Spin shim baked in
- Call this workflow for both PRs (ci.yaml) and main/tag release (release.yaml)
- Also run release.yaml on merges to main (albeit sans GH release when push to main)
- Update RELEASE_VERSION logic to support other refs (eg `refs/heads/main` where the 10 char split breaks)
I believe the intention is to eventually have spinkube/runtime-class-manager produce this image via fetching versioned shim releases from this repo, but this gets us an image with the latest shim version that we/users can plug in when installing the kwasm-operator chart, near-term.
Tested on fork eg https://github.com/vdice/containerd-shim-spin/actions/runs/8181643173
=> feat(*): add node installer dir and workflow

.github/workflows/docker-build-push.yaml
Mirrored PR: https://github.com/deislabs/containerd-wasm-shims/pull/212
This allows the CI to produce a single image manifest instead of an index.
=> ci(*): disable docker provenence

Cargo.lock, containerd-shim-spin/Cargo.toml, containerd-shim-spin/src/engine.rs
Note: this now only supports scratch containers pushed **without** the `--platform=wasi/wasm` flag set when building the container image.
relevant changes: https://github.com/spinkube/containerd-shim-spin/commit/7b1e07a99a6d1a2882609ddc66eed337565be90e
close #31 
Signed-off-by: Radu Matei <radu@fermyon.com>
=> Precompilation support.

Cargo.lock, containerd-shim-spin/Cargo.toml, containerd-shim-spin/src/main.rs
- also sets default log level of "error" now that we can configure a lower level than "info". This can be overwritten by setting `RUST_LOG` level for `containerd` process.
fixes https://github.com/spinkube/containerd-shim-spin/issues/39
=> fix: pull in termination patch from `runwasi`

node-installer/script/installer.sh
This commit changes how k3s is detected before restarting containerd. In some cases the `/etc/init.d/k3s` directory won't exist when running k3s. The ordering is also important because containerd can be run in parallel to k3s.
=> fix(node-installer): corrects the k3s distribution check

.github/workflows/build.yaml, .github/workflows/ci.yaml, .github/workflows/docker-build-push.yaml, .github/workflows/node-installer.yaml, .github/workflows/release.yaml
This should fix the warnings we see on github actions run. e.g. https://github.com/spinkube/containerd-shim-spin/actions/runs/8429881900
=> update github actions

Makefile, containerd-shim-spin/src/engine.rs, scripts/workloads-delete.sh
This PR adds a simple test case to validate that the pod is deleted successfully in a timely manner.
This PR also moves the signal handling to `run_wasi` function to ensure the pod can be terminated successfully even if the pod was requested to be deleted before the `run_trigger` function had setup the signals. Without this, there was a race condition between setting up of signals and receiving the signal, causing consistent failure on CI with the newly added testcase (and inconsistent failure when running locally)
=> add workload delete test and refactor signal handling in run_wasi function

.github/workflows/ci.yaml, Makefile, scripts/collect-debug-logs.sh
on failure, it will be nice to collect some debug logs that can help in debugging further. e.g. I am trying to [debug this failure](https://github.com/spinkube/containerd-shim-spin/actions/runs/8456341091/job/23166936399#step:8:861)
I saw that we collect some info in `workloads.sh`, but that won't be collected if the script fails before that.
=> allow ci to collect logs on failure

Cargo.lock, containerd-shim-spin/Cargo.toml, containerd-shim-spin/src/engine.rs
close #54 
This commit updates the Spin dependency to v2.4.0.
Draft until https://github.com/fermyon/spin-trigger-sqs/pull/19 is merged.
=> chore(*): Bump Spin dependency to v2.4.2

Cargo.lock, containerd-shim-spin/Cargo.toml, containerd-shim-spin/src/engine.rs
This commit allows Spin apps to be init containers, based on https://github.com/fermyon/spin-trigger-command: 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
name: spin-test-init
spec:
replicas: 1
selector:
matchLabels:
app: spin-test
template:
metadata:
labels:
app: spin-test
spec:
runtimeClassName: wasmtime-spin-v2
initContainers:
- name: spin-init
image: ttl.sh/spinkube-init:24h
command: ["/"]
containers:
- name: spin-test
image: ghcr.io/deislabs/containerd-wasm-shims/examples/spin-rust-hello:v0.10.0
command: ["/"]
ports:
- containerPort: 80
```
=> Support trigger command

.github/dependabot.yml, Cargo.lock
Adds dependabot to the repo and ran `cargo update` to update the deps to the latest. 
Closes #21
=> chore(*): add dependabot

.github/workflows/build.yaml, .github/workflows/ci.yaml, .github/workflows/node-installer.yaml, .github/workflows/release.yaml
The dependabot PR's are most likely failing because they are two separate PR's to update download/upload artifact action, and they are incompatible with each other.
This PR updates both of them in one go.
=> update download/upload artifact action

images/spin-inbound-redis/spin.toml
As of Spin [v2.4.0](https://github.com/fermyon/spin/releases/tag/v2.4.0), variable interpolation can be used for the redis trigger address.  It looks like the spin crates in the shim are at v2.4.2 as of writing, so it seems appropriate to update the example to use this feature.
=> feat(images): update spin-inbound-redis to use variable interpolation for address

Makefile, deployments/k3d/Makefile
since this repo only hosts the spin shim, there is no necessaity to continue to have a SHIMS variable in the makefile which uses for loops to loop through the shims to invoke commands.
this commit removes this logic entirely
=> refactor(makefile): remove SHIMS from makefile

README.md
the current readme does not provide information regarding documentation, feedback and contribution guide. This commit adds these crucial information to make the repo more developer friendly
=> docs: add more to the readme

tests/Cargo.toml, tests/src/integration_test.rs
=> update redis crate to 0.25

.github/dependabot.yml
this commit asks dependboto to ignore updates to wasmtime crate since it has to be done together with updates to Spin, which at the moment is done manually
=> ci(dependabot): ignore wasmtime

Cargo.lock, Cargo.toml, containerd-shim-spin/Cargo.toml, containerd-shim-spin/quickstart.md, deployments/k3d/README.md, deployments/workloads/workload.yaml, images/spin-dapr/README.md, images/spin-inbound-redis/Cargo.toml, images/spin-keyvalue/Cargo.toml, images/spin-outbound-redis/Cargo.toml, images/spin/Cargo.toml
In preparation to consume the Spin security patch: https://github.com/fermyon/spin/issues/2492
Patch must first be merged into the triggers and updated revisions should replace `TODO` in Cargo.toml:
- https://github.com/fermyon/spin-trigger-command/pull/15
- https://github.com/fermyon/spin-trigger-sqs/pull/22 
Note: updates to point to `spin-componentize` crate within Spin rather than the standalone repo which is now unmaintained.
Also, should bump versions to `v0.14.1` once dependencies are resolved
=> Use Spin v2.4.3 dependencies

Cargo.lock, containerd-shim-spin/Cargo.lock, containerd-shim-spin/Cargo.toml, containerd-shim-spin/src/engine.rs
Integrates `spin_telemetry` into the shim so that we get OTel support.
The workaround to prevent the panic is to point at versions of spin and spin triggers that don't use the [`tracing-log`](https://docs.rs/tracing-subscriber/0.3.18/tracing_subscriber/#optional-dependencies) feature.
=> Integrate spin_telemetry to support OTel

README.md
Since moving the Spin shim to its own repo, we now have no explicit instructions on how to install it. We may wish to add this documentation to the SpinKube [documentation](https://www.spinkube.dev/docs/containerd-shim-spin/) in addition or instead. I like the idea of having it in the shim repo because it will be easier to update with releases and having installation instructions seems like the bare minimum for repo READMEs.  I am happy to also contribute it to SpinKube documentation, as well.
=> Add installation documentation to the README

node-installer/script/installer.sh
Adds the ability for the `node-installer` image to identify and enable the `containerd-shim-spin` for k0s installations.
Tested with k0s latest, but should work for any k0s `>= 1.27.1`.
- https://docs.k0sproject.io/head/runtime/#k0s-managed-dynamic-runtime-configuration
=> feat: k0s support for node installer

containerd-shim-spin/src/engine.rs
Enables setting the shim's HTTP trigger listen address in `SPIN_HTTP_LISTEN_ADDR` (same naming scheme as [Spin CLI](https://github.com/fermyon/spin/pull/2547)). This can now be set in a container spec, which follows the approach of configuring the Spin runtime via container environment variables that is laid out in this [draft SKIP](https://github.com/spinkube/skips/pull/4).
closes https://github.com/spinkube/containerd-shim-spin/issues/52
related https://github.com/spinkube/containerd-shim-spin/issues/128
=> Support setting HTTP trigger listen address in env var

Cargo.lock, containerd-shim-spin/Cargo.toml
- Bump spin crates to [v2.6.0](https://github.com/fermyon/spin/releases/tag/v2.6.0)
- Bump wasmtime to 21.0.1 to [match version at Spin v2.6.0](https://github.com/fermyon/spin/blob/v2.6.0/Cargo.toml#L140)
- Bump spin-trigger-sqs to commit with similar Spin crate/wasmtime updates: https://github.com/fermyon/spin-trigger-sqs/commit/d01af1ed065e6562be3b00513b4c88f3526d677b
- Bump spin-trigger-command to commit with similar Spin crate/wasmtime updates: https://github.com/fermyon/spin-trigger-command/commit/87a514e38b2d4bb131ee6145cc3d730549e26f99
=> chore(shim/Cargo.toml): bump spin to 2.6.0 and wasmtime to 21.0.1

Cargo.lock, containerd-shim-spin/Cargo.toml
Nice prerequisite to the next release. I'll cut a v0.15 release once this is in.
=> Pin trigger dependencies to tagged releases

Cargo.lock, Cargo.toml, conformance-tests/Cargo.toml, conformance-tests/README.md, conformance-tests/src/main.rs
Spin has created a set of conformance test to ensure all Spin runtimes conform to baseline requirements/expectations
Status: runs conformance test to successful termination 🎉 
This is very draft:
- We need to decide how to push and pull the images to/from a registry for the tests. We may wish to push the images to a public registry before the tests.
- Determine how to implement TestEnvironment implementations for the shim without adding them to Spin core: https://github.com/kate-goldenring/spin/tree/shim-test-environment
=> Conformance Testing Setup for Shim

node-installer/script/installer.sh
I was testing with the latest v0.15.0 node-installer image and stumbled upon the following issue.
My K8s cluster happened to be a [KinD cluster](https://kind.sigs.k8s.io/) and yet the node-installer script thought I was using k0s and thus failed like so:
```
$ k -n kwasm logs pod/kind-worker2-provision-kwasm-724lt
touch: /mnt/node-root/etc/k0s/containerd.d/spin.toml: No such file or directory
```
It turns out that the current logic [here](https://github.com/spinkube/containerd-shim-spin/blob/main/node-installer/script/installer.sh#L31) will exit 0 because the latter `grep` process itself is successfully found -- whereas it should not be counted.
For example, on my kind-worker node:
```
root@kind-worker:/# ps aux | grep kubelet | grep /var/lib/k0s/bin/kubelet
root        1820  0.0  0.0 …
```
=> fix(node-installer): avoid false positive via grep process itself

Cargo.lock, containerd-shim-spin/Cargo.toml, containerd-shim-spin/src/engine.rs
Prefixes all container env vars with `SPIN_VARIABLE`. This means that Spin components can get access to these variables if specifically configured in the Spin manifest to have access. For example, say a a component wants access to the `KUBERNETES_SERVICE_ADDRESS` container environment variable, it would configure this in the Spin.toml as follows:
```sh
[variables]
kubernetes_service_address = { required = true }
[component.example]
source = "target/wasm32-wasi/release/example.wasm"
allowed_outbound_hosts = []
[component.example.variables]
kubernetes_service_address = "{{ kubernetes_service_address }}"
```
Then, it can be accessed in the Spin app using the variables SDK:
```rust
let addr = variables::get("kubernetes_service_address")?;
```
Should affect/reflect the "Configuring Runtime …
=> Make container environment variables accessible as application variables

node-installer/script/installer.sh
=> feat(node-installer): #153 conditionally restart k0s controller service when present

README.md, scripts/setup-linux.sh
1. change `make run-spin` to `make run`
2. fix an error encountered in setup-linux.sh
=> readme & setup: simplify the run command and fix an error in setup-linux.sh

README.md
- Adds a section describing which build artifacts are produced for what events
- Adds a TOC at the top of the README for easier navigation
=> docs(README.md): add build artifact section; add TOC

containerd-shim-spin/src/constants.rs, containerd-shim-spin/src/engine.rs, containerd-shim-spin/src/main.rs, containerd-shim-spin/src/source.rs, containerd-shim-spin/src/stdio_hook.rs, containerd-shim-spin/src/trigger.rs, containerd-shim-spin/src/utils.rs
this commit organized code to different modules:
- constants: to handling constants across entire crate
- engine: the execution engine
- source: manages application sources
- stdio_hook: a trigger hook for stdio
- trigger: manages spin triggers
- utils: utility functions
it also removes ResolvedAppSource as it's not needed
=> shim: organize code to different modules

rust-toolchain.toml
This is necessary because Spin now requires this version of Rust.
=> Require Rust version 1.79 or above

.github/workflows/release.yaml, CHANGELOG.md, release.md, scripts/extract-changelog.sh
* [CHANGELOG: add CHANGELOG.md](https://github.com/spinkube/containerd-shim-spin/commit/86b7cfcf04177496ab98442224e5d21634d8dd33) 
* [scripts, .github/workflows/release.yaml: add script to extract changelog](https://github.com/spinkube/containerd-shim-spin/commit/cfd46c52040ab7bd124ff93d867c3d5ea8fe79bd)
=> Add `CHANGELOG.md` to the repo

CHANGELOG.md
The `extract-changelog.sh` script expects the released version to be declared in `CHANGELOG.md` in the following format:
1. Following a subheader definition (`##`)
2. Inside brackets -- I assume this is to link to the release as I've done here
Note, whether or not it is a pre-release is now expected to be in the tag name according to the release workflow. When creating releases, I normally modify the release afterwards to say that it is a prerelease. I hesitate to add `-pre` to the end of our tags when we have not been doing that previously and i think of anything less than semver `1.0.0` to be pre-release
=> fix(docs): update CHANGELOG.md formatting for v0.16.0 release

.github/workflows/release.yaml
I believe that the `create release` step is currently failing due to lack of access to the `RELEASE_NOTES.md` file created in the previous step.
Alternative approach would be to upload and then download the `RELEASE_NOTES.md` file in separate steps.
=> fix(release): update release workflow to make changelog available

containerd-shim-spin/src/engine.rs
Musl builds of the shim throw a libunwind error during startup due to Wasmtime failing to detect which unwind implementation to use. For now, turn off generating native unwind info. A fix was added to Wasmtime https://github.com/bytecodealliance/wasmtime/pull/9479 and should be in the 27.0.0 release. At that point we can turn this back on if desired.
fixes https://github.com/spinkube/containerd-shim-spin/issues/210
=> fix: remove native unwind info

containerd-shim-spin/src/constants.rs, containerd-shim-spin/src/trigger.rs
fixes https://github.com/spinkube/containerd-shim-spin/issues/216
=> fix: configure Spin state dir

containerd-shim-spin/src/engine.rs
We currently do not have a way to surface runwasi errors to K8s events. They are only being surfaced in containerd logs which are not intuitive to search. Just as we print trigger information on startup, it makes sense to print error reasons for the time being to make them easier to discover. Take an app with components `hello` and `goodbye`. If i selectively deploy component `foo`, I will now see the following log in the container log:
```sh
Error with selective deployment: Specified component "foo" not found in application
```
Example SpinApp:
```
apiVersion: core.spinkube.dev/v1alpha1
kind: SpinApp
metadata:
name: hello-salutation-spinap-foop
spec:
image: "ghcr.io/kate-goldenring/spin-operator/examples/spin-salutations:20241022-144454"
replicas: 1
executor: containerd-shim-spin …
```
=> Print selective deployment error to container stdio

Cargo.lock, containerd-shim-spin/Cargo.toml
- Bump spin crates to [v3.0.0](https://github.com/fermyon/spin/releases/v3.0.0)
- Bump spin trigger plugins (mqtt, sqs, command) to match
- Bump wasmtime to match (22 -> 25)
=> chore(*): bump spin and co crates per spin v3.0.0

containerd-shim-spin/src/constants.rs, containerd-shim-spin/src/trigger.rs
Instead of fixing the `state_dir`, we can set the `local_app_dir` which is [a fallback](https://github.com/fermyon/spin/blob/b98c996201b7fc198cc746b7d78a97d8afcb64d2/crates/runtime-config/src/lib.rs#L223) if the `state_dir` is not set in runtime config like so:
```toml
state_dir = "/Path/to/state-dir/
```
I confirmed this fix works with the following steps using a [simple TODO app](https://github.com/rylev/spin-todo) that creates a SQLite DB in the state store:
```console
$ git clone git@github.com:rylev/spin-todo.git
$ cd spin-todo
$ mkdir foo
$ echo state_dir=\"/.configured" > runtime-config.toml
$ spin build
$ spin registry push ttl.sh/spin-sqlite-todo-123:48h 
$ spin kube scaffold --from ttl.sh/spin-sqlite-todo-123:48h --replicas 1 --runtime-config-file _scratch/runtime-config.toml | …
```
=> fix: enable configuring state_dir with runtime configuration

images/spin/Dockerfile, rust-toolchain.toml, scripts/deploy-workloads.sh, tests/src/integration_test.rs, tests/workloads-common/mqtt-broker.yaml, tests/workloads-pushed-using-docker-build-push/workloads.yaml, tests/workloads-pushed-using-spin-registry-push/workloads.yaml
Seeing if switching back to using a local emqx broker will resolve the mqtt tests failing. ref https://github.com/spinkube/containerd-shim-spin/issues/257
=> fix: switch to using EMQX MQTT broker for e2e tests

CHANGELOG.md, Cargo.lock, containerd-shim-spin/Cargo.toml
Pulls in release of Spin that fixes issue with dropped Redis connections. Draft until the triggers are released
=> Bump dependencies to Spin v3.1.2

README.md
The ReadMe includes a couple of Kubernetes YAML manifests which should be deployed when installing the containerd-shim-spin. These manifests are not valid k8s resources due to minor indention errors.
This fixes the indention to provide a smooth user experience for new users.
=> docs: fix yaml indentation for k8s manifests

Cargo.lock, containerd-shim-spin/Cargo.toml
This enables the opentelemetry feature from the containerd-shim-wasm which provides otel for the shim process. Before `containerd-shim-wasm v0.9.0`, the container process would inherit the otel runtime from the shim process, and thus causing a conflict with the spin telemetry runtime. Now, the container process was initialized (a.k.a zygote process) at the very begining when the shim process is in a clean state, and so it is free to initialize it's own otel runtime. 
This PR builds on top of #271 
FYI @calebschoepp
=> feat(otel): Enable opentelemetry for the Spin shim

.github/workflows/action-node-installer.yaml
closes: https://github.com/spinframework/containerd-shim-spin/issues/298
=> Script MicroK8s installation in node installer tests

.github/workflows/action-node-installer.yaml, README.md, conformance-tests/README.md, node-installer/script/installer.sh, node-installer/tests/Dockerfile.minikube-custom, node-installer/tests/integration-test-k3s.sh, node-installer/tests/integration-test-kind.sh, node-installer/tests/integration-test-microk8s.sh, node-installer/tests/integration-test-minikube.sh
update `README.md`, `conformance-tests/README.md`, `node-installer/script/installer.sh` to include `SystemdCgroup` option in containerd runtime options.
Please take a look @kate-goldenring 
**question**: do we have any test cases for node-installer? 
**follow up**: to follow address #180 , we need to add some test cases to verify the pod metric is now showing up with the updated node-installer. 
Closes #285
=> feat: add SystemCgroup option to containerd runtime options

node-installer/script/installer.sh
- **node-installer: detect containerd config version instead of $IS_K3S**
- **node-installer: K3S & RKE2 can detect spin shim, no need to configure**
- **node-installer: fix K3S by linking shim to PATH**
As discussed in https://github.com/spinframework/containerd-shim-spin/issues/231#issuecomment-2756971572
=> node-installer: fixes for containerd 2

node-installer/script/installer.sh
Currently, rerunning the node-installer causes this error due to a preexisting link:
```sh
Events:
Type    Reason   Age   From     Message
----    ------   ----  ----     -------
Normal  Pulling  15s   kubelet  Pulling image "ghcr.io/spinframework/containerd-shim-spin/node-installer:20250331-171727-g57712f0"
Normal  Pulled   13s   kubelet  Successfully pulled image "ghcr.io/spinframework/containerd-shim-spin/node-installer:20250331-171727-g57712f0" in 2.138s (2.138s including waiting). Image size: 29342804 bytes.
Normal  Created  13s   kubelet  Created container: kwasm-provision
Normal  Started  13s   kubelet  Started container kwasm-provision
Kates-MacBook-Pro :: ~ » k logs aks-agentpool-39718514-vmss000000-provision-kwasm-f9wlf -n kwasm
ln: …
```
=> Force update shim path symbolic link if one already exists

deployments/workloads/workload.yaml, node-installer/tests/integration-test-k3s.sh
follow up to https://github.com/spinframework/containerd-shim-spin/pull/303#discussion_r2021751890
node installer tests should not be triggered (and fail) since PRing from fork
=> chore: bump workload tag for v0.19.0
